using System.Threading.Channels;

namespace Week_10_Challenge_Labs
{
    internal class Program
    {
        static void Main(string[] args)
        {

            #region Q # 1
            /*
            You are given two strings s and t.
            String t is generated by random shuffling string s and then add one more letter at a random position.
            Return the letter that was added to t.

            char addedLetter = ' ';
            
            for (int i = 0, j = 0; i < t.Length; j++)
            {
                if (j == s.Length)
                {
                    addedLetter = t[i];
                    break;
                }

                if (t[i] == s[j])
                {
                    i++;
                    j = 0;
                    
                }

            }

            Console.WriteLine(addedLetter);
            */
            #endregion
            Console.WriteLine("----- Added Letter -----");
            string s = "abcd", t = "abcde";
            Console.WriteLine("Input1: " + s);
            Console.WriteLine("Input2: " + t);
            string u = s + t;
            int result = 0;

            foreach (char c in u) result ^= c;

            Console.WriteLine("Output: " + (char)result);

            #region Q # 2
            /*
                You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.
                Merge nums1 and nums2 into a single array sorted in non-decreasing order.
                The final sorted array should not be returned by the function, but instead be stored inside the array nums1. To accommodate this, nums1 has a length of m + n, where the first m
                elements denote the elements that should be merged, and the last n elements are set to 0 and should be ignored. nums2 has a length of n.
                 */
            #endregion
            Console.WriteLine("\n----- Merged Array -----");
            int[] nums1 = [1, 2, 3, 0, 0, 0];
            int m = 3;
            int[] nums2 = [2, 5, 6];
            int n = 3;
            Console.WriteLine("First Array: [" + string.Join(", ", nums1) + "]");
            Console.WriteLine("Second Array: [" + string.Join(", ", nums2) + "]");

            int length = m + n - 1;

            for (int i = m - 1, j = n - 1; j >= 0;)
            {
                if (i >= 0 && nums1[i] > nums2[j])
                    nums1[length--] = nums1[i--];
                else
                    nums1[length--] = nums2[j--];
              }
            Console.WriteLine("Merged Array: [" + string.Join(", ", nums1) + "]");
        }

    }

}
